### ISSUE TITLE
在vue3.2.1下报错

### ISSUE THREAD

**Issue by wzh1995524** [author-fuyf/slider-verify-v3#1]
onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

**Comment by author-fuyf** [comment]
> onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

未复现，应非当前插件影响。
请参考 [https://deepscan.io/docs/rules/vue-misused-api-after-await]( https://deepscan.io/docs/rules/vue-misused-api-after-await)  希望能定位你的问题
