### ISSUE TITLE
刷新有时候会导致小块拼图消失

### ISSUE THREAD

**Issue by GoCross** [author-fuyf/slider-verify-v3#2]
![验证图片](https://user-images.githubusercontent.com/40139388/133387935-a8819c42-bf68-4723-a892-ffec6e5a524c.png)
并且一般来说不是图刷出来就没有，而是图出来之后零点几秒才消失。

**Comment by author-fuyf** [comment]
> ![验证图片](https://user-images.githubusercontent.com/40139388/133387935-a8819c42-bf68-4723-a892-ffec6e5a524c.png) 并且一般来说不是图刷出来就没有，而是图出来之后零点几秒才消失。

感谢你的指出 经过测试 在移动端高频点击触发校验时会触发当前问题
很抱歉 这迟来的修复处理 最新修复版本已发布更新（v1.1.2）
