### ISSUE TITLE
"align-item:center", 这个是不是少了一个s

### ISSUE THREAD

**Issue by soonio** [author-fuyf/slider-verify-v3#3]
位置：https://github.com/author-fuyf/slider-verify-v3/blob/9bb531349d6a1c7518b650aa1299625d80e495fd/src/components/SliderVerify/index.vue#L528

```
▲ [WARNING] "align-item" is not a known CSS property

    <stdin>:1:55329:
      1 │ ...a-v-292de9b8]{display:flex;align-item:center}#slider-verify #ver...
        │                               ~~~~~~~~~~
        ╵                               align-items

  Did you mean "align-items" instead?

```

**Comment by author-fuyf** [comment]
> 位置：
> 
> https://github.com/author-fuyf/slider-verify-v3/blob/9bb531349d6a1c7518b650aa1299625d80e495fd/src/components/SliderVerify/index.vue#L528
> 
> ```
> ▲ [WARNING] "align-item" is not a known CSS property
> 
>     <stdin>:1:55329:
>       1 │ ...a-v-292de9b8]{display:flex;align-item:center}#slider-verify #ver...
>         │                               ~~~~~~~~~~
>         ╵                               align-items
> 
>   Did you mean "align-items" instead?
> ```

感谢你的指出 我的疏忽导致的问题
很抱歉 这迟来的修复处理 最新修复版本已发布更新（v1.1.2）
